version: 0.3-{build}
skip_tags: true
build_script:
- cmd: >-
    appveyor.bat
on_failure:
- 7z a -mx9 -r fail.7z *.exe *.sln *.txt *.log
- appveyor.exe PushArtifact fail.7z
shallow_clone: true
test: off
artifacts:
- path: hidrun_x64.exe
- path: hidrunwait_x64.exe
- path: hidrun_x86.exe
- path: hidrunwait_x86.exe
- path: hidrun.7z